{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ include "haproxy-ingress.name" . }}
    chart: {{ include "haproxy-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "haproxy-ingress.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "haproxy-ingress.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "haproxy-ingress.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ include "haproxy-ingress.fullname" . }}
{{- end -}}
