{{- if .Values.controller.template -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "haproxy-ingress.name" . }}
    chart: {{ include "haproxy-ingress.chart" . }}
    component: "{{ .Values.controller.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "haproxy-ingress.controller.fullname" . }}-template
  namespace: {{ .Release.Namespace }}
data:
  haproxy.tmpl: |-
{{ .Values.controller.template | indent 4 }}
{{/* .Files.Get "haproxy.tmpl" | indent 4 */}}
{{- end }}
